
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PeopleProTraining.Dal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int EmployeeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Salary { get; set; }

    public string StartDate { get; set; }

    public int BuildingBuildingId { get; set; }

    public int DepartmentDepartmentId { get; set; }



    public virtual Building Building { get; set; }

    public virtual Department Department { get; set; }

}

}
